services:
  books_store_db:
    ports:
      - 5432:5432
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      - POSTGRES_DB=books_shops_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres